apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-app-deployment
  labels:
    app: golang-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang-app
  template:
    metadata:
      labels:
        app: golang-app
    spec:
      containers:
      - name: golang-app-containers
        image: us-west1-docker.pkg.dev/alpine-theory-411710/kubernetes-go-lang/go-lang-app:v2
        env:
        - name: IMAGE_TAG
          value: %SHORT_COMMIT%
        ports:
        - containerPort: 8080
